version: '2'
services:
  kodimariadb:
    restart: unless-stopped
    build:
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: "some_crazy-passwordTHATIthoughtUp!"
    volumes:
      - /srv/docker/kodimariadb/data:/var/lib/mysql
    ports:
      - "3306:3306"
